# tclutils -- umbrella package for selected Tcl utility modules
package require Tcl 8.6-
package require tclutils::common 0.1
package require tclutils::tufind 0.1
package require tclutils::tugrep 0.1
package require tclutils::tufuzzy 0.1
package require tclutils::tuagrep 0.1
package require tclutils::tuwc 0.1
package require tclutils::tustrings 0.1
package require tclutils::tuhexdump 0.1
package require tclutils::tubin 0.1
package require tclutils::tuhexedit 0.1
package require tclutils::tused 0.1
package require tclutils::tudiff 0.1
package require tclutils::tupatch 0.1
package require tclutils::tucat 0.1
package require tclutils::tuhead 0.1
package require tclutils::tutail 0.1
package require tclutils::tusort 0.1
package require tclutils::tuuniq 0.1
package require tclutils::tucut 0.1
package require tclutils::tupaste 0.1
package require tclutils::tujoin 0.1
package require tclutils::tuzip 0.1
package require tclutils::tuzipfs 0.1
package require tclutils::tujson 0.1
package require tclutils::tuxml 0.1
package require tclutils::tucsv 0.1
package require tclutils::tuod 0.1
package require tclutils::tuiconv 0.1
package require tclutils::tucmp 0.1
package require tclutils::tutee 0.1
package require tclutils::tuxargs 0.1
package require tclutils::tusplit 0.1
package require tclutils::tucsplit 0.1
package require tclutils::tucomm 0.1
package require tclutils::tufold 0.1
package require tclutils::tustat 0.1
package require tclutils::tubase64 0.1
package require tclutils::tucrc 0.1
package require tclutils::tutr 0.1
package require tclutils::tuodf 0.1
package require tclutils::tupdf 0.1
package require tclutils::tumd 0.1
package require tclutils::tufile 0.1
package require tclutils::tuawk 0.1
package require tclutils::tucal 0.1
package require tclutils::tucode 0.1
package require tclutils::tunl 0.1
package require tclutils::tuseq 0.1
package require tclutils::turev 0.1
package require tclutils::tutac 0.1
package require tclutils::tuexpand 0.1
package require tclutils::tushuf 0.1
package require tclutils::tucolumn 0.1
package require tclutils::tupr 0.1
package require tclutils::tutsort 0.1
package require tclutils::tunumfmt 0.1
package require tclutils::tunotes 0.1
package require tclutils::tuldif 0.1
package require tclutils::tuical 0.1
package require tclutils::tuini 0.1
package require tclutils::tuvcard 0.1
package require tclutils::tuhash 0.1
package require tclutils::tupath 0.1
package require tclutils::tusize 0.1
package require tclutils::tubase32 0.1
package require tclutils::tuuuid 0.1
package require tclutils::tufmt 0.1
package require tclutils::tudate 0.1
package require tclutils::tuurl 0.1
package require tclutils::tuevent 0.1
package require tclutils::turegistry 0.1
package require tclutils::tudav 0.1
package require tclutils::tuholiday 0.1
package require tclutils::turrule 0.1
package require tclutils::tuopen 0.1
package require tclutils::tubookmark 0.1
package require tclutils::tulog 0.1
package require tclutils::tuimage 0.1
package require tclutils::tupng 0.1
package provide tclutils 0.49.0
