.TH tujson 1 0.29.0 tclutils "User Commands"
.SH NAME
 tujson \- JSON helper command
.SH SYNOPSIS
 tujson validate ?file.json?
.br
 tujson minify ?file.json?
.br
 tujson pretty ?file.json?
.br
 tujson parse ?file.json?
.br
 tujson parseTyped ?file.json?
.SH DESCRIPTION
 tujson reads JSON from a file or stdin and validates, formats, minifies, or
parses it into Tcl dictionary/list syntax.
