'" Copyright (c) 2026 Gregor Ebbing
'" SPDX-License-Identifier: MIT
.TH tuodf 1 0.29.0 tclutils "User Commands"
.SH NAME
tuodf \- command-line wrapper for tclutils::tuodf.
.SH SYNOPSIS
.nf
tclsh bin/tuodf.tcl text file.odt
tclsh bin/tuodf.tcl parts file.odt
tclsh bin/tuodf.tcl create out.odt ?-title T?
.fi
.SH DESCRIPTION
.PP
Print text, list container members, or create a simple ODT from stdin lines.
.SH SEE ALSO
tuodf(n)
