'" Copyright (c) 2026 Gregor Ebbing
'" SPDX-License-Identifier: MIT
.TH tupdf 1 0.29.0 tclutils "User Commands"
.SH NAME
tupdf \- command-line wrapper for tclutils::tupdf.
.SH SYNOPSIS
.nf
tclsh bin/tupdf.tcl summary file.pdf
tclsh bin/tupdf.tcl object file.pdf N
tclsh bin/tupdf.tcl metadata file.pdf
.fi
.SH DESCRIPTION
.PP
Prints basic PDF structure information without external tools.
.SH SEE ALSO
tupdf(n)
