.TH TUZIPFS 1 "2026-05-30" "tclutils 0.18.0"
.SH NAME
.tuzipfs \- Tcl 9 ZipFS helper
.SH SYNOPSIS
.B tclsh bin/tuzipfs.tcl available
.br
.B tclsh bin/tuzipfs.tcl mount ZIP ?NAME?
.br
.B tclsh bin/tuzipfs.tcl list MOUNT ?GLOB?
.SH DESCRIPTION
Small command-line wrapper for the tclutils::tuzipfs package.
